# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_DATABASE=grab
      - image: circleci/postgres
        environment:
          - POSTGRES_USER: moove
          - POSTGRES_DB: location_service

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/MOOVE-Network/location_service
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.09.0-ce
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install python-pip
            sudo pip install awscli
      - run:
          name: Waiting for mysql to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for mysql && exit 1
      - run:
          name: Waiting for pg to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for pg && exit 1
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure
      - run:
          name: test
          command: ./test.sh
          environment:
            LOCATION_PG_DATABASE_URL: postgres://moove:m00ve4wd@clustering-pg-test.ct3tozaserta.ap-southeast-1.rds.amazonaws.com/location_service?sslmode=disable
      - run: 
          name: build binaries
          command: |
            make linux
            mv location_service location_service_linux
            make mac
            mv location_service location_service_osx
      - store_artifacts:
          path: /go/src/github.com/MOOVE-Network/location_service/location_service_linux
          destination: location_service_linux
      - store_artifacts:
          path: /go/src/github.com/MOOVE-Network/location_service/location_service_osx
          destination: location_service_osx
      - store_artifacts:
          path: /go/src/github.com/MOOVE-Network/location_service/coverage.html
          destination: coverage.html
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t moove/location_service:$TAG .
          docker tag moove/location_service:$TAG $DOCKER_REGISTRY_BARE/moove/location_service:$TAG
          docker tag moove/location_service:$TAG $DOCKER_REGISTRY_BARE/moove/location_service:latest
          aws configure set region $AWS_REGION
          eval $(aws ecr get-login --no-include-email)
          docker push $DOCKER_REGISTRY_BARE/moove/location_service:$TAG
          docker push $DOCKER_REGISTRY_BARE/moove/location_service:latest
